spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/my_postgres?useSSL=false
    driver-class-name: org.postgresql.Driver
    username: my_postgres
    password: 111111

mybatis:
  type-handlers-package: com.jhy.section2.dao
  mapper-locations: classpath:mapper/*.xml

